# PIPELINE DEFINITION
# Name: basic-pipeline
# Description: This pipeline does basic ETL and Stats gen
components:
  comp-display-data:
    executorLabel: exec-display-data
  comp-load-data:
    executorLabel: exec-load-data
deploymentSpec:
  executors:
    exec-display-data:
      container:
        args:
        - --data_path=gs://kubeflow_demo
        command:
        - python3
        - /legacy_code_repo/display_data.py
        image: asia-south1-docker.pkg.dev/mlendtoend/artifact/display_data
    exec-load-data:
      container:
        args:
        - --data_path=gs://kubeflow_demo
        command:
        - python3
        - /legacy_code_repo/load_data.py
        image: asia-south1-docker.pkg.dev/mlendtoend/artifact/load_data
pipelineInfo:
  description: This pipeline does basic ETL and Stats gen
  name: basic-pipeline
root:
  dag:
    tasks:
      display-data:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-display-data
        taskInfo:
          name: display-data
      load-data:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-load-data
        taskInfo:
          name: load-data
schemaVersion: 2.1.0
sdkVersion: kfp-2.6.0
